statisticsnorway/jupyterhub-onprem

docker/jupyterlab/Dockerfile
docker/jupyterlab/bashrc.felles

the idea is that check-git-config.sh will be called from bashrc.felles. bashrc.felles is sourced from every home directory

moved everything from env.sh to bashrc.felles and added gitconfig support

---

docker/jupyterlab/bashrc.felles

/etc/skel/.bashrc is updated in common: https://github.com/statisticsnorway/jupyterlab-common/pull/7

calling /etc/skel/.bashrc in bashrc.felles

---

docker/jupyterlab/bashrc.felles

PIP_REQUIRE_VIRTUALENV is removed, the value is now set in jupyterlab-common.
https://github.com/statisticsnorway/jupyterlab-common/pull/14/files

Remove environment variables for PIP_REQUIRE_VIRTUALENV

---

docker/jupyterlab/Dockerfile

PIP_REQUIRE_VIRTUALENV is Finally set, same changes as https://github.com/statisticsnorway/jupyterhub-project/blob/main/docker/jupyterlab/Dockerfile#L141
Gives user ownership of cache, same changes as https://github.com/statisticsnorway/jupyterhub-project/blob/main/docker/jupyterlab/Dockerfile#L59

Copy changes from jupyterhub-project

---

docker/jupyterlab/Dockerfile

add ssb-project 1.0.5

---

docker/jupyterlab/Dockerfile

Remove chown /home/jovyan/.cache

Ssb project v1.0.5

---

docker/jupyterhub/Dockerfile
docker/jupyterhub/azure-pipelines.yml

This should also trigger an update of sssd-tools, which will fix PAM authentication

Update base jupyterhub image

---

docker/jupyterlab/Dockerfile

Note that ssb-datadoc should not have GCS support

Update dapla-toolbelt, datadoc and ssb-project-cli

---

docker/jupyterlab/Dockerfile

Add new package to jupyter on-prem

Add python package saspy

---

docker/jupyterlab/Dockerfile

https://github.com/statisticsnorway/datadoc/releases/tag/v0.2.4

ssb-datadoc.v0.2.4

---

docker/jupyterlab/Dockerfile

- Add dapla-team-cli
- Update ssb-project-cli
- Update dapla-toolbelt

Update dapla-toolbelt and ssb-project-cli

---

docker/jupyterlab/Dockerfile

This error is related to https://github.com/python-poetry/poetry/issues/3249

Fix for Poetry not respecting PIP_INDEX_URL

---

docker/jupyterlab/Dockerfile

Change pulls CA-certificate from nexus and adds it to /etc/ssl/certs
related to #50

pulling certificate from nexus and running update-ca-certificates

---

docker/jupyterlab/Dockerfile

- Upgrade ssb-project-cli to v1.1.0
- Install kvakk-git-tools v2.2.1
- ssb_gitconfig.py is added in [jupyterlab-common#53](https://github.com/statisticsnorway/jupyterlab-common/pull/53)

Add validation for gitconfig

---

docker/jupyterlab/Dockerfile

The same change as in [jupyterhub-project#109](https://github.com/statisticsnorway/jupyterhub-project/pull/109) , take a look at that PR for more information.

Set ssb-project template version to 1.0.1

---

docker/jupyterlab/Dockerfile

https://github.com/statisticsnorway/ssb-project-cli/releases/tag/v1.1.5

Bump ssb-project to 1.1.5

---

docker/jupyterlab/Dockerfile

https://github.com/statisticsnorway/datadoc/releases/tag/v0.3.0

Bump datadoc to 0.3.0

---

docker/jupyterlab/Dockerfile

add conda lib to ld library path to fix bug in PS-38824

---

docker/jupyterlab/bashrc.felles

Reverts statisticsnorway/jupyterhub-onprem#76

Revert "export instead of source"

---

docker/jupyterlab/Dockerfile
docker/jupyterlab/bashrc.felles

Reverts statisticsnorway/jupyterhub-onprem#75

Revert "Fix pipx"

---

docker/jupyterlab/Dockerfile

Bump dapla-toolbelt and datadoc

---

deploy/jupyterhub/azure-pipelines.yml
deploy/jupyterlab/azure-pipelines.yml
docker/jupyterhub/.env.prod

- Prod compose env uses the AR images
- Prevent triggering on PR

Prevent Azure Pipelines triggering on PR

---

docker/jupyterlab/Dockerfile

Same change as https://github.com/statisticsnorway/jupyterhub-project/pull/159

Update base image repository to the new registry

---

docker/jupyterhub/.env.prod
docker/jupyterhub/.env.staging
docker/jupyterhub/jupyterhub_config.py
docker/jupyterlab/Dockerfile

Jira ref: https://statistics-norway.atlassian.net/browse/DPSTAT-747

Add environment variables for service identification

---

docker/jupyterlab/Dockerfile

See changes in: https://github.com/statisticsnorway/ssb-project-template-stat/pull/70

Update ssb-project template version

---

docker/jupyterlab/Dockerfile

Reverts statisticsnorway/jupyterhub-onprem#144

Revert "Fix installation of oracle sqlplus"

---

docker/jupyterlab/Dockerfile

install libgit2-dev

---

docker/jupyterlab/Dockerfile

Some error comes from internal Nexus. we switched it to another proxy server. this solves the issue.

Nexus error with pygmets fixed

---

docker/jupyterlab/Dockerfile
docker/jupyterlab/requirements.txt

added ipydatagrid after aei requested. Fixed issue with nano, updated poetry and added nox. also added poetry shell. and nox poetry.

Fixed bugs and added new dependencies to jupyterlab
